---
- name: "Activity Monitor - Show the main window when launching Activity Monitor"
  osx_defaults: { domain: 'com.apple.ActivityMonitor', key: 'OpenMainWindow', type: bool, value: "{{ ActivityMonitor_OpenMainWindow }}" }
  when: ActivityMonitor_OpenMainWindow is defined
  notify: restart ActivityMonitor

- name: "Activity Monitor - Activity Monitor Dock Icon"
  osx_defaults: { domain: 'com.apple.ActivityMonitor', key: 'IconType', type: int, value: "{{ ActivityMonitor_IconType }}" }
  when: ActivityMonitor_IconType is defined
  notify: restart ActivityMonitor

- name: "Activity Monitor - Show all processes in Activity Monitor"
  osx_defaults: { domain: 'com.apple.ActivityMonitor', key: 'ShowCategory', type: int, value: "{{ ActivityMonitor_ShowCategory }}" }
  when: ActivityMonitor_ShowCategory is defined
  notify: restart ActivityMonitor
