---

- name: "Application Firewall - Global State"
  osx_defaults: { domain: '/Library/Preferences/com.apple.alf', key: 'globalstate', type: int, value: "{{ item.value }}" }
  with_items:
    - { name: "Off", value: 0 }
    - { name: "On", value: 1 }
    - { name: "Block All Incoming Connections", value: 2 }
  when: ApplicationFirewall_GlobalState is defined and item.name == ApplicationFirewall_GlobalState
  become: true

- name: "Application Firewall - Allow Downloaded Signed Software"
  osx_defaults: { domain: '/Library/Preferences/com.apple.alf', key: 'allowdownloadsignedenabled', type: int, value: "{{ item.value }}" }
  with_items:
    - { name: "Disabled", value: 0 }
    - { name: "Enabled", value: 1 }
  when: ApplicationFirewall_AllowDownloadSigned is defined and item.name == ApplicationFirewall_AllowDownloadSigned
  become: true

- name: "Application Firewall - Allow Built-in Software"
  osx_defaults: { domain: '/Library/Preferences/com.apple.alf', key: 'allowsignedenabled', type: int, value: "{{ item.value }}" }
  with_items:
    - { name: "Disabled", value: 0 }
    - { name: "Enabled", value: 1 }
  when: ApplicationFirewall_AllowSigned is defined and item.name == ApplicationFirewall_AllowSigned
  become: true

- name: "Application Firewall - Enable Logging"
  osx_defaults: { domain: '/Library/Preferences/com.apple.alf', key: 'loggingenabled', type: int, value: "{{ item.value }}" }
  with_items:
    - { name: "Disabled", value: 0 }
    - { name: "Enabled", value: 1 }
  when: ApplicationFirewall_Logging is defined and item.name == ApplicationFirewall_Logging
  become: true

- name: "Application Firewall - Global State"
  osx_defaults: { domain: '/Library/Preferences/com.apple.alf', key: 'loggingoption', type: int, value: "{{ item.value }}" }
  with_items:
    - { name: "throttled", value: 0 }
    - { name: "brief", value: 1 }
    - { name: "detail", value: 2 }
  when: ApplicationFirewall_LoggingOption is defined and item.name == ApplicationFirewall_LoggingOption
  become: true

- name: "Application Firewall - Stealth Mode"
  osx_defaults: { domain: '/Library/Preferences/com.apple.alf', key: 'stealthenabled', type: bool, value: "{{ item.value }}" }
  with_items:
    - { name: "Disabled", value: 0 }
    - { name: "Enabled", value: 1 }
  when: ApplicationFirewall_Stealth is defined and item.name == ApplicationFirewall_Stealth
  become: true
