---
- block:
  - name: "Disk Images - Disable disk image verification"
    osx_defaults: { domain: 'com.apple.frameworks.diskimages', key: 'skip-verify', type: bool, value: "{{ DiskImages_SkipVerify }}" }
    when: DiskImages_SkipVerify is defined

  - name: "Disk Images - Disable locked disk image verification"
    osx_defaults: { domain: 'com.apple.frameworks.diskimages', key: 'skip-verify-locked', type: bool, value: "{{ DiskImages_SkipVerifyLocked }}" }
    when: DiskImages_SkipVerifyLocked is defined

  - name: "Disk Images - Disable remote disk image verification"
    osx_defaults: { domain: 'com.apple.frameworks.diskimages', key: 'skip-verify-remote', type: bool, value: "{{ DiskImages_SkipVerifyRemote }}" }
    when: DiskImages_SkipVerifyRemote is defined
  # Privilege escalation to `target_user_id` is only required for inner steps when
  # the `target_user_id` doesn't match the `ansible_user_id`
  become: "{{ (target_user_id != ansible_user_id) | bool }}"
  become_user: "{{ target_user_id }}"
