---
- name: "Login Window - Toggle login for hidden user '>Console'"
  osx_defaults: { domain: '/Library/Preferences/com.apple.loginwindow', key: 'DisableConsoleAccess', type: bool, value: "{{ LoginWindow_DisableConsoleAccess }}" }
  when: LoginWindow_DisableConsoleAccess is defined
  become: true

- name: "Login Window - Toggle guest login"
  osx_defaults: { domain: '/Library/Preferences/com.apple.loginwindow', key: 'GuestEnabled', type: bool, value: "{{ LoginWindow_GuestEnabled }}" }
  when: LoginWindow_GuestEnabled is defined
  become: true

- name: "Login Window - Add a message to the login screen"
  osx_defaults: { domain: '/Library/Preferences/com.apple.loginwindow', key: 'LoginwindowText', type: string, value: "{{ LoginWindow_LoginwindowText }}" }
  when: LoginWindow_LoginwindowText is defined
  become: true

- name: "Check if login screen background image exists"
  stat: path={{ LoginWindow_DesktopPicture }}
  changed_when: false
  register: LoginWindow_DesktopPicture_New

- name: "Login Window - Change login screen background"
  osx_defaults: { domain: '/Library/Preferences/com.apple.loginwindow', key: 'DesktopPicture', type: string, value: "{{ LoginWindow_DesktopPicture }}" }
  when: LoginWindow_DesktopPicture is defined  and LoginWindow_DesktopPicture != "" and LoginWindow_DesktopPicture_New.stat.exists
  become: true

- name: "Login Window - Disable shutdown and restart button on login Window"
  osx_defaults: { domain: '/Library/Preferences/com.apple.loginwindow', key: 'PowerOffDisabled', type: bool, value: "{{ LoginWindow_ShutDownDisabled }}" }
  when: LoginWindow_ShutDownDisabled is defined
  become: true

- name: "Login Window - Show input menu"
  osx_defaults: { domain: '/Library/Preferences/com.apple.loginwindow', key: 'showInputMenu', type: bool, value: "{{ LoginWindow_showInputMenu }}" }
  when: LoginWindow_showInputMenu is defined
  become: true

- name: "Login Window - Show password hints - Retries until hint"
  osx_defaults: { domain: '/Library/Preferences/com.apple.loginwindow', key: 'RetriesUntilHint', type: int, value: "{{ LoginWindow_RetriesUntilHint }}" }
  when: LoginWindow_RetriesUntilHint is defined
  become: true

- name: "Login Window - Display Login Window as list or fields"
  osx_defaults: { domain: '/Library/Preferences/com.apple.loginwindow', key: 'SHOWFULLNAME', type: bool, value: "{{ item.value }}" }
  with_items:
    - { name: "List of users", value: 0 }
    - { name: "Name and password", value: 1 }
  when: LoginWindow_Display is defined and item.name == LoginWindow_Display
  become: true
