---
- name: "Spotlight - Building orderedItems"
  set_fact:
    orderedItems: "{{ orderedItems| default([]) | combine( { item }) }}"
  with_items: {{ Spotlight_OrderedItems }}
  when: Spotlight_OrderedItems is defined

- name: "Spotlight - Indexing Items"
  osx_defaults: { domain: 'com.apple.safari', key: 'orderedItems', type: array, value: "{{ Spotlight_OrderedItems }}" }
  when: orderedItems is defined and orderedItems != []
  notify: restart Spotlight
