---
- name: restart ActivityMonitor
  command: killall "Activity Monitor"
  ignore_errors: yes

- name: restart AppStore
  command: killall "App Store"
  ignore_errors: yes

- name: restart MenuBar
  command: killall SystemUIServer
  ignore_errors: yes

- name: restart Dock
  command: killall Dock
  ignore_errors: yes

- name: restart Finder
  command: killall Finder
  ignore_errors: yes

- name: restart Safari
  command: killall Safari
  ignore_errors: yes

- name: restart Spotlight
  command: killall mds
  become: true
  ignore_errors: yes

- name: restart LaunchServices
  command: killall launchservicesd
  become: true
  ignore_errors: yes
